version: "3"

services:
  php_fpm:
    build: .
    container_name: php_fpm
    entrypoint: dockerize -template docker/app/.env:.env  -wait tcp://db:3306 -timeout 40s docker/entrypoint.sh
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:
      - .:/var/www
    networks:
      - app-networks
    depends_on:
      - db
      - redis
  nginx:
    build: docker/nginx
    container_name: nginx
    restart: always
    tty: true
    entrypoint: dockerize -template docker/app/nginx.conf:docker/nginx/nginx.conf nginx -g 'daemon off;'
    environment:
      - APP_PHP=php_fpm
      - APP_PHP_PORT=9000
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - app-networks
    depends_on:
      - php_fpm
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - "33060:3306"
    volumes:
      - ../.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-networks
  redis:
    image: redis:alpine
    expose:
      - 6379
    networks:
      - app-networks
networks:
  app-networks:
    driver: bridge
